name = "padi-plug-connect-worker"
account_id = "213c2009d0d9bb97f27da3054d7af944"
workers_dev = true
compatibility_date = "2026-08-07"

# TanStack Start / Nitro generated Worker
main = ".output/server/index.mjs"

[vars]
SUPABASE_URL = "https://lhmrvpvbhymtqqkyystr.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxobXJ2cHZiaHltdHFxa3l5c3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwNDE4MDEsImV4cCI6MjEwMTYxNzgwMX0.2d16X4Fc4L3gnKFjZVC_DOpM-NBnAZfF4TkqGoKlym8"