
-- Add local-language labels
ALTER TABLE public.categories
  ADD COLUMN IF NOT EXISTS name_yo TEXT,
  ADD COLUMN IF NOT EXISTS name_ha TEXT,
  ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 100;

-- Seed / upsert full brief taxonomy
INSERT INTO public.categories (kind, slug, name, name_yo, name_ha, sort_order) VALUES
-- ===== PRODUCTS =====
('product','fashion','Fashion & Style','Aṣọ & Ẹwà','Kaya & Salo',10),
('product','ankara','Ankara & African Prints','Aṣọ Ankara','Ankara',11),
('product','shoes','Shoes & Footwear','Bàtà','Takalma',12),
('product','bags','Bags & Accessories','Àpò','Jaka',13),
('product','jewelry','Jewelry','Ohun-ọ̀ṣọ́','Kayan Ado',14),
('product','watches','Watches','Aago Ọwọ́','Agogo',15),
('product','beauty','Beauty & Personal Care','Ẹwà','Kwalliya',20),
('product','skincare','Skincare','Ìtọ́jú Awọ','Kula da Fata',21),
('product','haircare','Hair Care & Wigs','Ìrun','Gashi',22),
('product','perfumes','Perfumes & Oils','Òórùn Dídùn','Turare',23),
('product','food','Food & Groceries','Oúnjẹ','Abinci',30),
('product','snacks','Snacks & Drinks','Ìpanu','Kayan Ci',31),
('product','spices','Spices & Ingredients','Ata & Tùràrí','Kayan Yaji',32),
('product','frozen','Frozen Foods','Oúnjẹ Tútù','Sanyi Abinci',33),
('product','electronics','Electronics','Ẹrọ Ìmọ̀ Ẹrọ','Na''ura',40),
('product','phones','Phones & Tablets','Fóònù','Waya',41),
('product','laptops','Laptops & Computers','Kọ̀ǹpútà','Kwamfuta',42),
('product','audio','Audio & Headphones','Agbọ́rọ́sọ','Na''urar Sauti',43),
('product','gaming','Gaming','Eré','Wasa',44),
('product','tv','TV & Home Cinema','Tẹlifíṣọ̀n','Talabijin',45),
('product','home','Home & Living','Ilé','Gida',50),
('product','furniture','Furniture','Ohun-èlò Ilé','Kayan Daki',51),
('product','kitchen','Kitchen & Cookware','Ohun-èlò Ìdáná','Kayan Kicin',52),
('product','bedding','Bedding & Linen','Aṣọ Ìbùsùn','Kayan Kwana',53),
('product','decor','Home Decor','Ìṣe Ọ̀ṣọ́ Ilé','Ado Gida',54),
('product','appliances','Appliances','Ẹrọ Ilé','Kayan Aiki',55),
('product','baby','Baby & Kids','Ọmọ Kékeré','Yara',60),
('product','toys','Toys & Games','Aroba','Kayan Wasa',61),
('product','school','School & Stationery','Ilé-ìwé','Makaranta',62),
('product','books','Books & Media','Ìwé','Littattafai',63),
('product','fitness','Fitness & Sports','Ìdárayá','Wasanni',70),
('product','outdoor','Outdoor & Camping','Ìta','Waje',71),
('product','automotive','Automotive','Ọkọ̀','Mota',72),
('product','tools','Tools & Hardware','Ohun-èlò','Kayan Aiki',73),
('product','pets','Pet Supplies','Ẹranko Ilé','Dabbobin Gida',74),
('product','garden','Garden & Outdoor','Ọgbà','Lambu',75),
('product','office','Office Supplies','Ọ́fíìsì','Ofis',76),
('product','health','Health & Wellness','Ìlera','Lafiya',77),
('product','herbal','Herbal & Wellness','Àgbọ','Magani',78),
('product','art','Art & Crafts','Iṣẹ́ Ọwọ́','Fasaha',79),
('product','made-in-africa','Made in Africa','Ṣe Ní Áfíríkà','An Yi a Afirka',80),
('product','handmade','Handmade','Ìṣe Ọwọ́','Aikin Hannu',81),
('product','vintage','Vintage & Second-hand','Àtijọ́','Tsofaffi',82),
('product','musical','Musical Instruments','Ohun-èlò Orin','Kayan Kida',83),
('product','religious','Religious Items','Ohun-ẹ̀sìn','Kayan Addini',84),
('product','wedding','Wedding & Events','Ìgbéyàwó','Aure',85),
('product','digital','Digital Products','Ohun-èlò Dígítà','Kayan Dijital',86),
('product','gifts','Gifts & Souvenirs','Ẹbùn','Kyaututtuka',87),
('product','stationery','Party Supplies','Ohun-èlò Àsè','Kayan Biki',88),
('product','farm','Farm Produce','Èso Ọgbà','Amfanin Gona',89),

-- ===== SERVICES / ARTISANS =====
('service','tailoring','Tailoring','Aránṣọ','Dinki',10),
('service','fashion-design','Fashion Design','Àpẹrẹ Aṣọ','Zanen Kaya',11),
('service','shoemaking','Shoe Making & Repair','Àṣàbàtà','Yin Takalma',12),
('service','bead','Bead & Jewelry Making','Ìlẹ̀kẹ̀','Yin Beads',13),
('service','hair-braiding','Hair & Braiding','Ìrun Dídì','Kitso',20),
('service','barber','Barbering','Igbá-orí','Wanzanci',21),
('service','makeup','Makeup Artistry','Ìtọjú Ojú','Kwalliya',22),
('service','nails','Nail Technician','Èékánná','Kusoshi',23),
('service','spa','Spa & Massage','Ìfọwọ́rọ','Tausa',24),
('service','carpentry','Carpentry','Kíkọ́lé','Kafinta',30),
('service','plumbing','Plumbing','Ẹ̀rọ Omi','Fanfo',31),
('service','electrical','Electrical','Iná Mọ̀nàmọ́ná','Wutar Lantarki',32),
('service','welding','Welding & Metalwork','Ìsomọ́','Sarkakiya',33),
('service','painting','Painting & Finishing','Iṣẹ́ Àwọ','Fenti',34),
('service','tiling','Tiling & Masonry','Tail & Bíríkì','Tayil',35),
('service','ac-repair','AC & Fridge Repair','Ìtọjú Ẹrọ','Gyaran AC',36),
('service','generator','Generator Repair','Ẹrọ Iná','Gyaran Janareta',37),
('service','solar','Solar Installation','Iná Oòrùn','Hasken Rana',38),
('service','cleaning','Cleaning','Ìmọ́tótó','Tsaftace Gida',40),
('service','laundry','Laundry & Dry Cleaning','Ìfọṣọ','Wanke Kaya',41),
('service','fumigation','Fumigation & Pest Control','Ìpa Kòkòrò','Kashe Kwari',42),
('service','moving','Moving & Delivery','Gbígbé Ẹrù','Motsi',43),
('service','catering','Catering','Sísè','Girki',50),
('service','chef','Private Chef','Òṣèfẹ̀','Kuku Na Musamman',51),
('service','baking','Baking & Pastries','Búrẹ́ẹ́dì','Toya',52),
('service','events','Events & Décor','Ètò Ayẹyẹ','Shirya Biki',53),
('service','mc','MC & Comedy','Alásọtàn','Mai Gabatarwa',54),
('service','photography','Photography','Yíya Fọ́tò','Daukar Hoto',55),
('service','videography','Videography','Yíya Fídíò','Daukar Bidiyo',56),
('service','dj','DJ & Sound','DJ','DJ',57),
('service','music','Music & Instruments','Orin','Kida',58),
('service','tutoring','Home Tutoring','Kọ́ni','Karantarwa',60),
('service','music-lessons','Music Lessons','Ìkọ́ Orin','Koyar da Kida',61),
('service','driving','Driving Lessons','Ìwakọ̀','Koyon Tuki',62),
('service','fitness-coach','Fitness Coaching','Olùkọ́ Ìdárayá','Kocin Motsa Jiki',63),
('service','yoga','Yoga & Wellness','Yoga','Yoga',64),
('service','graphics','Graphic Design','Àpẹrẹ Àwòrán','Zanen Zane',70),
('service','branding','Branding','Àmì','Alama',71),
('service','web','Web Development','Ìdàgbàsókè Wẹ́ẹ̀bù','Web',72),
('service','app-dev','App Development','Ìdàgbàsókè Áàpù','Manhaja',73),
('service','social-media','Social Media Management','Aṣagbaṣe Mídíà','Sarrafa Kafofin',74),
('service','digital-marketing','Digital Marketing','Ìpolówó Dígítà','Talla',75),
('service','content','Content Writing','Ìkọ́wé','Rubutu',76),
('service','translation','Translation & Interpretation','Ìtumọ̀','Fassara',77),
('service','printing','Printing & Branding','Títẹ̀','Bugu',78),
('service','tv-repair','Phone & Laptop Repair','Ìtọ́jú Fóònù','Gyaran Waya',80),
('service','mechanic','Auto Mechanic','Ìtọjú Ọkọ̀','Injiniyan Mota',81),
('service','car-wash','Car Wash & Detail','Ìfọ Ọkọ̀','Wanke Mota',82),
('service','security','Security Services','Aabo','Tsaro',83),
('service','babysitting','Babysitting & Nannies','Ìtọjú Ọmọ','Kula da Yara',84),
('service','elder','Elder Care','Ìtọjú Àgbà','Kula da Tsofaffi',85),
('service','legal','Legal Services','Òfin','Shari''a',86),
('service','accounting','Bookkeeping & Tax','Ìṣirò','Lissafi',87),
('service','realestate','Real Estate Agent','Àṣojú Ilẹ̀','Wakilin Kadara',88),
('service','pet-services','Pet Grooming & Care','Ìtọjú Ẹranko','Kula da Dabbobi',89)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  name_yo = EXCLUDED.name_yo,
  name_ha = EXCLUDED.name_ha,
  sort_order = EXCLUDED.sort_order,
  kind = EXCLUDED.kind;
